/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.niraj.Controller;

import com.niraj.Controller.Account;
import com.niraj.Controller.BankControllerInterface;
import com.niraj.Controller.BankControllerMYSQL;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author nakarmi23
 */
public class CreateAccount extends javax.swing.JPanel {

    BankControllerInterface dc = new BankControllerMYSQL();
    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccountNumberLabel = new javax.swing.JLabel();
        AccountNameLabel = new javax.swing.JLabel();
        OpeningBalanceLabel = new javax.swing.JLabel();
        AccountTypeLabel = new javax.swing.JLabel();
        AccountNumberInput = new javax.swing.JTextField();
        AccountNameInput = new javax.swing.JTextField();
        OpeningBalanceInput = new javax.swing.JTextField();
        AccountTypeComboBox = new javax.swing.JComboBox<>();
        SubmitButton = new javax.swing.JButton();

        AccountNumberLabel.setText("Account Number");

        AccountNameLabel.setText("Account Name");

        OpeningBalanceLabel.setText("Opening Balance");

        AccountTypeLabel.setText("Account Type");

        AccountTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Current", "Fixed", "Saving" }));
        AccountTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountTypeComboBoxActionPerformed(evt);
            }
        });

        SubmitButton.setText("Submit");
        SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccountNumberLabel)
                            .addComponent(AccountNameLabel)
                            .addComponent(OpeningBalanceLabel)
                            .addComponent(AccountTypeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccountNumberInput)
                            .addComponent(AccountNameInput)
                            .addComponent(OpeningBalanceInput)
                            .addComponent(AccountTypeComboBox, 0, 259, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SubmitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccountNumberLabel)
                    .addComponent(AccountNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccountNameLabel)
                    .addComponent(AccountNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OpeningBalanceLabel)
                    .addComponent(OpeningBalanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccountTypeLabel)
                    .addComponent(AccountTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SubmitButton)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AccountTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountTypeComboBoxActionPerformed

    private void SubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMouseClicked
        Account newAccount;       // TODO add your handling code here:
        newAccount = new Account(Integer.parseInt(AccountNumberInput.getText()), AccountNameInput.getText(), Integer.parseInt(OpeningBalanceInput.getText()), String.valueOf(AccountTypeComboBox.getSelectedItem()).charAt(0));
        
        if(dc.newAccount(newAccount))
                JOptionPane.showMessageDialog(SwingUtilities.windowForComponent(this), "Account Created successfully.");
        else
                JOptionPane.showMessageDialog(SwingUtilities.windowForComponent(this), "Cannot create account.");
    }//GEN-LAST:event_SubmitButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountNameInput;
    private javax.swing.JLabel AccountNameLabel;
    private javax.swing.JTextField AccountNumberInput;
    private javax.swing.JLabel AccountNumberLabel;
    private javax.swing.JComboBox<String> AccountTypeComboBox;
    private javax.swing.JLabel AccountTypeLabel;
    private javax.swing.JTextField OpeningBalanceInput;
    private javax.swing.JLabel OpeningBalanceLabel;
    private javax.swing.JButton SubmitButton;
    // End of variables declaration//GEN-END:variables
}
