/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.niraj.Controller;

import com.niraj.Controller.BankControllerInterface;
import com.niraj.Controller.BankControllerMYSQL;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author nakarmi23
 */
public class DeleteAccount extends javax.swing.JPanel {

    BankControllerInterface dc = new BankControllerMYSQL();
    /**
     * Creates new form DeleteAccount
     */
    public DeleteAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccountNumberLabel = new javax.swing.JLabel();
        AccountNumberInput = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();

        AccountNumberLabel.setText("Account Number");

        SubmitButton.setText("Submit");
        SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AccountNumberLabel)
                        .addGap(18, 18, 18)
                        .addComponent(AccountNumberInput, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SubmitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccountNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountNumberLabel))
                .addGap(18, 18, 18)
                .addComponent(SubmitButton)
                .addContainerGap(205, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMouseClicked
        
        switch(dc.delete(Integer.parseInt(AccountNumberInput.getText()))){
            case 0:
                   JOptionPane.showMessageDialog(SwingUtilities.windowForComponent(this), "Something went wrong while trying to delete your account. Please try again.");
                   break;
            case 1:
                JOptionPane.showMessageDialog(SwingUtilities.windowForComponent(this), "Your account was deleted successfully.");
                   break;
            case 2:
                JOptionPane.showMessageDialog(SwingUtilities.windowForComponent(this), "Account does not exits. Enter a valid account number.");
                   break;
            case 3:
                JOptionPane.showMessageDialog(SwingUtilities.windowForComponent(this), "Please make sure your account has a balance of 0.");
                   break;
        }
    }//GEN-LAST:event_SubmitButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountNumberInput;
    private javax.swing.JLabel AccountNumberLabel;
    private javax.swing.JButton SubmitButton;
    // End of variables declaration//GEN-END:variables
}
