/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.niraj.Controller;

import com.niraj.Controller.BankControllerInterface;
import com.niraj.Controller.BankControllerMYSQL;
import java.awt.GridLayout;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author nakarmi23
 */
public class Deposit extends javax.swing.JPanel {
    BankControllerInterface dc = new BankControllerMYSQL();
    /**
     * Creates new form Deposit
     */
    public Deposit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccountNumberLabel = new javax.swing.JLabel();
        AccountNumberInput = new javax.swing.JTextField();
        DepositAmountInput = new javax.swing.JTextField();
        DepositAmountLabel = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        message = new javax.swing.JLabel();

        AccountNumberLabel.setText("Account Number");

        DepositAmountLabel.setText("Deposit Amount");

        SubmitButton.setText("Submit");
        SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AccountNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccountNumberInput))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DepositAmountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(message)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SubmitButton))
                            .addComponent(DepositAmountInput, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccountNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountNumberLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DepositAmountInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepositAmountLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton)
                    .addComponent(message))
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMouseClicked
        // TODO add your handling code here:
        System.out.println(AccountNumberInput.getText());
        switch(dc.deposit(Integer.parseInt(AccountNumberInput.getText()), Integer.parseInt(DepositAmountInput.getText()))){
            case 0:
                   JOptionPane.showMessageDialog(SwingUtilities.windowForComponent(this), "Something went wrong while trying to deposit thw amount. Please try again.");
                   break;
            case 1:
                JOptionPane.showMessageDialog(SwingUtilities.windowForComponent(this), "The Amount was deposited successfully.");
                   break;
            case 2:
                JOptionPane.showMessageDialog(SwingUtilities.windowForComponent(this), "Your account does not exits. Enter a valid account number.");
                   break;
        }
    }//GEN-LAST:event_SubmitButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountNumberInput;
    private javax.swing.JLabel AccountNumberLabel;
    private javax.swing.JTextField DepositAmountInput;
    private javax.swing.JLabel DepositAmountLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
