/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.niraj.Controller;

import com.niraj.Controller.BankControllerInterface;
import com.niraj.Controller.BankControllerMYSQL;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author nakarmi23
 */
public class FundTransfer extends javax.swing.JPanel {

    BankControllerInterface dc = new BankControllerMYSQL();
    /**
     * Creates new form FundTransfer
     */
    public FundTransfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FromAccountLabel = new javax.swing.JLabel();
        ToAccountLabel = new javax.swing.JLabel();
        TransferAmount = new javax.swing.JLabel();
        FromAccountInput = new javax.swing.JTextField();
        ToAccountInput = new javax.swing.JTextField();
        TransferAmountInput = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();

        FromAccountLabel.setText("From Account");

        ToAccountLabel.setText("To Account");

        TransferAmount.setText("Transfer Amount");

        SubmitButton.setText("Submit");
        SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FromAccountLabel)
                            .addComponent(ToAccountLabel)
                            .addComponent(TransferAmount))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FromAccountInput)
                                    .addComponent(ToAccountInput)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TransferAmountInput, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SubmitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FromAccountLabel)
                    .addComponent(FromAccountInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToAccountLabel)
                    .addComponent(ToAccountInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TransferAmount)
                    .addComponent(TransferAmountInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SubmitButton)
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMouseClicked
        int fromAccount = Integer.parseInt(FromAccountInput.getText());
        int toAccount = Integer.parseInt(ToAccountInput.getText());
        int amount = Integer.parseInt(TransferAmountInput.getText());
        
        switch(dc.fundTransfer(fromAccount, toAccount, amount)){
            case 0:
                JOptionPane.showMessageDialog(SwingUtilities.windowForComponent(this), "Something went wrong while trying to transfering fund. Please try again");
                   
                   break;
            case 1:
                JOptionPane.showMessageDialog(SwingUtilities.windowForComponent(this), "Fund Transfer was successfully.");
                   break;
            case 2:
                JOptionPane.showMessageDialog(SwingUtilities.windowForComponent(this), "From or To account does not exits. Enter a valid account number.");
                   break;
            case 3:
                JOptionPane.showMessageDialog(SwingUtilities.windowForComponent(this), "Transfer amount was greater than balance aviliable in From Amount.");
                   break;
        }
    }//GEN-LAST:event_SubmitButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FromAccountInput;
    private javax.swing.JLabel FromAccountLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField ToAccountInput;
    private javax.swing.JLabel ToAccountLabel;
    private javax.swing.JLabel TransferAmount;
    private javax.swing.JTextField TransferAmountInput;
    // End of variables declaration//GEN-END:variables
}
