/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.niraj.Controller;

import com.niraj.Controller.Deposit;
import com.niraj.Controller.FundTransfer;
import com.niraj.Controller.DeleteAccount;
import com.niraj.Controller.CreateAccount;
import java.awt.GridLayout;

/**
 *
 * @author nakarmi23
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        ViewPanel.setLayout(new GridLayout(1, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        ViewPanel = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        ExitMenuItem = new javax.swing.JMenuItem();
        AccountMenu = new javax.swing.JMenu();
        ViewAllAccountMenuItem = new javax.swing.JMenuItem();
        CreateAccountMenuItem = new javax.swing.JMenuItem();
        DeleteAccountMenuItem = new javax.swing.JMenuItem();
        TransactionMenu = new javax.swing.JMenu();
        DepositMenuItem = new javax.swing.JMenuItem();
        WithdrawMenuItem = new javax.swing.JMenuItem();
        FundTransferMenuItem = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout ViewPanelLayout = new javax.swing.GroupLayout(ViewPanel);
        ViewPanel.setLayout(ViewPanelLayout);
        ViewPanelLayout.setHorizontalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ViewPanelLayout.setVerticalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        getContentPane().add(ViewPanel, java.awt.BorderLayout.CENTER);

        FileMenu.setText("File");

        ExitMenuItem.setText("Exit");
        ExitMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMenuItemMousePressed(evt);
            }
        });
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(ExitMenuItem);

        MenuBar.add(FileMenu);

        AccountMenu.setText("Account");

        ViewAllAccountMenuItem.setText("View All Account");
        ViewAllAccountMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewAllAccountMenuItemMousePressed(evt);
            }
        });
        AccountMenu.add(ViewAllAccountMenuItem);

        CreateAccountMenuItem.setText("Create New Account");
        CreateAccountMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CreateAccountMenuItemMousePressed(evt);
            }
        });
        AccountMenu.add(CreateAccountMenuItem);

        DeleteAccountMenuItem.setText("Delete Account");
        DeleteAccountMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DeleteAccountMenuItemMousePressed(evt);
            }
        });
        AccountMenu.add(DeleteAccountMenuItem);

        MenuBar.add(AccountMenu);

        TransactionMenu.setText("Transaction");

        DepositMenuItem.setText("Deposit");
        DepositMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DepositMenuItemMousePressed(evt);
            }
        });
        TransactionMenu.add(DepositMenuItem);

        WithdrawMenuItem.setText("Withdraw");
        WithdrawMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                WithdrawMenuItemMousePressed(evt);
            }
        });
        TransactionMenu.add(WithdrawMenuItem);

        FundTransferMenuItem.setText("Fund Transfer");
        FundTransferMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FundTransferMenuItemMousePressed(evt);
            }
        });
        TransactionMenu.add(FundTransferMenuItem);

        MenuBar.add(TransactionMenu);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    private void ExitMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMenuItemMousePressed
        System.exit(0);
    }//GEN-LAST:event_ExitMenuItemMousePressed

    private void DepositMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositMenuItemMousePressed
        
        ViewPanel.removeAll();
        Deposit deposit = new Deposit();
        ViewPanel.add(deposit);
        deposit.setVisible(true);
        ViewPanel.revalidate();
        ViewPanel.repaint();
    }//GEN-LAST:event_DepositMenuItemMousePressed

    private void WithdrawMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WithdrawMenuItemMousePressed
        
        ViewPanel.removeAll();
        Withdraw withdraw = new Withdraw();
        ViewPanel.add(withdraw);
        withdraw.setVisible(true);
        ViewPanel.revalidate();
        ViewPanel.repaint();
    }//GEN-LAST:event_WithdrawMenuItemMousePressed

    private void CreateAccountMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccountMenuItemMousePressed
       
        ViewPanel.removeAll();
        CreateAccount createAccount = new CreateAccount();
        ViewPanel.add(createAccount);
        createAccount.setVisible(true);
        ViewPanel.revalidate();
        ViewPanel.repaint();
    }//GEN-LAST:event_CreateAccountMenuItemMousePressed

    private void DeleteAccountMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAccountMenuItemMousePressed
        ViewPanel.removeAll();
        DeleteAccount deleteAccount = new DeleteAccount();
        ViewPanel.add(deleteAccount);
        deleteAccount.setVisible(true);
        ViewPanel.revalidate();
        ViewPanel.repaint();
    }//GEN-LAST:event_DeleteAccountMenuItemMousePressed

    private void ViewAllAccountMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAllAccountMenuItemMousePressed
        ViewPanel.removeAll();
        ViewAllAccount viewAllAccount = new ViewAllAccount();
        ViewPanel.add(viewAllAccount);
        viewAllAccount.setVisible(true);
        ViewPanel.revalidate();
        ViewPanel.repaint();
    }//GEN-LAST:event_ViewAllAccountMenuItemMousePressed

    private void FundTransferMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FundTransferMenuItemMousePressed
        ViewPanel.removeAll();
        FundTransfer fundTransfer = new FundTransfer();
        ViewPanel.add(fundTransfer);
        fundTransfer.setVisible(true);
        ViewPanel.revalidate();
        ViewPanel.repaint();
    }//GEN-LAST:event_FundTransferMenuItemMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AccountMenu;
    private javax.swing.JMenuItem CreateAccountMenuItem;
    private javax.swing.JMenuItem DeleteAccountMenuItem;
    private javax.swing.JMenuItem DepositMenuItem;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem FundTransferMenuItem;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu TransactionMenu;
    private javax.swing.JMenuItem ViewAllAccountMenuItem;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JMenuItem WithdrawMenuItem;
    private javax.swing.JMenu jMenu3;
    // End of variables declaration//GEN-END:variables
}
